name: cos publish
on:
  push:
    branches:
      - release/*
jobs:
  publish-cos:
    runs-on: ubuntu-latest
    env:
      DOCS_GA_ID: G-GPRCVYSQSG
    strategy:
      matrix:
        node: ['16']
    name: Build and publish
    steps:
      - uses: actions/checkout@v2

      - name: Config coscmd
        run: |
          echo "${{ secrets.COS_CONFIG_YAML }}" > ~/.cos.yaml

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'
      - run: yarn
      - run: yarn docs:build

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install coscmd
        run: |
          wget https://github.com/tencentyun/coscli/releases/download/v0.10.2-beta/coscli-linux
          mv coscli-linux coscli
          chmod 755 coscli
          ./coscli --version
          
      - name: Upload docs to SH
        run: |
          ./coscli cp docs/.vuepress/dist/ cos://power-wechat-docs-1307679408/ -r --thread-num 20

      - name: Upload docs to SG
        run: |
          ./coscli cp docs/.vuepress/dist/ cos://power-wechat-docs-s-1307679408/ -r --thread-num 20
