name: Release

on:
  push:
    tags:
      - v*
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    name: Release Dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Tailscale
        uses: tailscale/github-action@main
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

      - name: Setup node env 🏗
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node }}
          check-latest: true
      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 7.0.0
          run_install: false
      - name: Install dependencies
        run: |
          pnpm install --shamefully-hoist --frozen-lockfile
      - name: Build
        run: pnpm build

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - id: coscli
        uses: wangchaoyi/qcloud-cos-deploy-action@main
        with:
          secret_id: ${{ secrets.COS_SH_APP_ID }}
          secret_key: ${{ secrets.COS_SH_APP_KEY }}
          token: ""
          buckets: ${{ secrets.COS_SH_BUCKET }}
          region: ap-shanghai
      - name: Upload docs to SH
        run: |
          export https_proxy=http://100.91.137.50:1089
          export http_proxy=http://100.91.137.50:1089
          export all_proxy=socks5://100.91.137.50:1089
          coscli cp .vitepress/dist/ cos://power-wechat-docs-1307679408/ -r --thread-num 20


